### ISSUE TITLE
SSL missing

### ISSUE THREAD

**Issue by OmgImAlexis** [BraveUX/braveux#190]
@ekfuhrmann Your site along with any subdomains and other projects should really have SSL/TLS enabled especially since Let's Encrypt is 100% free.

Ref: https://github.com/BraveUX/for-the-badge/issues/31

**Comment by ekfuhrmann** [comment]
I see you closed this. Just wanted to give you a heads up that we will be pushing out SSL shortly along with a site update.

Thanks for the looking out. Going to reopen this for the time being until it gets pushed out with the update.

**Comment by ekfuhrmann** [comment]
Site now redirects to HTTPS.
