### ISSUE TITLE
FOR THE BADGE - footer

### ISSUE THREAD

**Issue by leefinkel** [BraveUX/braveux#205]
![image](https://cloud.githubusercontent.com/assets/10156853/26409446/99e63fd0-406e-11e7-853e-80b3c82c48e5.png)

Center the VIEW ALL octagon inside the lighter gray column.

Delete: DESIGNED BY CA  BUILT BY MC & JAX
Center "A BRAVE UX ENDEAVOR"

**Comment by ekfuhrmann** [comment]
https://github.com/BraveUX/for-the-badge/issues/54
