### ISSUE TITLE
Hero scaling off – forcing horizontal scroll

### ISSUE THREAD

**Issue by jgbrave** [BraveUX/braveux#219]
![IMG_4877.PNG](https://images.zenhubusercontent.com/5966211761b4ca3b0a7429c0/2440ee69-41a1-4ef3-9ead-0924e60c29c3)

![IMG_4875.PNG](https://images.zenhubusercontent.com/5966211761b4ca3b0a7429c0/d08c8283-bb2f-4a6c-9d39-2ebdce6c783b)

**Comment by ekfuhrmann** [comment]
Fixed this issue with the following commit: e549d98c1efce4b0dd4e40bbd9200416ba5ed1d8
