### ISSUE TITLE
Wrong fonts in product images on the ID Auto Case Study

### ISSUE THREAD

**Issue by theseangoodwin** [BraveUX/braveux#224]
Looks like Myriad is the font in the app images. It should be Roboto Condensed.

**Comment by ekfuhrmann** [comment]
Assigning this to @theseangoodwin as it's a matter of updating the asset itself. Let me know if someone else should be assigned to it.

**Comment by theseangoodwin** [comment]
Since we're redesigning this case study, we no longer have to worry about this
