### ISSUE TITLE
Audit Case Study Frames

### ISSUE THREAD

**Issue by ekfuhrmann** [BraveUX/braveux#228]
Case Study Frames include Mobile iOS device, Mobile Android device, iPad (landscape), iPad (portrait), and Desktop browser window. For each frame, we currently have 5 different color kits for styling our devices based on the needs of the case study; however, we really only ever use 3 of them across all of our projects. In addition, the frames we use 

These color kits make use of a **Primary** and **Secondary** color that then is distributed throughout the frame. The newest iOS frame that was added really makes use moreso of a 3 color theme, as opposed to 2... which is fine, but we should look to update all of our frames and colors.

What I would like done is for us to come up with **Three** color kits for each device. These color kits must make use of the same color (ie. dark kit uses #282828 as primary, and #333333 as secondary, regardless of device). We can include a third color in there for additional contrast/gradient fill, but it again must be consistent with the other frames. 

That said, we can also make exceptions to these kits, such as desktop only using 2 colors as opposed to 3 (should we opt to move to a 3 color kit).

Specifically what I'm looking for is updated SVG's comprised of up to **three** colors for every device. The colors must be consistent across all devices. Once each device has been designed and the color kits figured out, we will add all of them at once in order to update the frames across the site.

Tagging @tpatton89 so that this is on your radar for future planning.

This issue will require a full QC pass on **all** previous case studies so as to make sure they don't conflict with any of the original color themes of that project.

**Comment by ekfuhrmann** [comment]
For additional assistance, these are the current color kit themes we use. Feel free to modify/delete as you see fit @theseangoodwin 

![image](https://user-images.githubusercontent.com/8878152/28840075-cda810ec-76c3-11e7-9cfb-9c8e602c56ac.png)

**Comment by ekfuhrmann** [comment]
@theseangoodwin Just reminding you about this issue in case it has fallen to the wayside.

**Comment by ekfuhrmann** [comment]
@theseangoodwin see #285 for Gabriela feedback

**Comment by theseangoodwin** [comment]
@ekfuhrmann updated frames live in this folder:

https://www.dropbox.com/sh/1wvrrh0124wrd50/AADsqXAtsoBNvyn8ys-lv5B0a?dl=0

**Comment by ekfuhrmann** [comment]
@theseangoodwin Frames are now updated on the site. I'm going to create a new issue for a follow-up update in which you take a look at the colors + shadow modifiers we currently have for frames.
