### ISSUE TITLE
B-Line Case Study: "Fly through management tasks"  

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#238]
![screen shot 2017-11-22 at 10 30 31 am](https://user-images.githubusercontent.com/31738798/33135462-6eeb8fec-cf70-11e7-9c86-6d8c8d9a80a5.png)

Should the animation be slightly slower?

**Comment by ekfuhrmann** [comment]
The animation speed is consistent across the site for all block animations.
