### ISSUE TITLE
B-Line Case Study "Contact Hours"

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#239]
![screen shot 2017-11-22 at 10 34 22 am](https://user-images.githubusercontent.com/31738798/33135566-c02b469a-cf70-11e7-8fa3-0d94e7e69dee.png)

Not sure if this is purposeful or not, but the left and right cards are not aligned (left is slightly higher than the right) - though i could see that being a purposeful thing.

**Comment by ekfuhrmann** [comment]
This was intentional based off the design.
