### ISSUE TITLE
B-Line Case Study "Provide an organized workspace" 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#240]
![screen shot 2017-11-22 at 10 36 50 am](https://user-images.githubusercontent.com/31738798/33135696-1e6b8666-cf71-11e7-98aa-5c6d1e20bd6c.png)

The image is slightly blurry

**Comment by ekfuhrmann** [comment]
We try to keep the best resolution while still maintaining reasonable file sizes.
