### ISSUE TITLE
B-Line: "Contacts" Resizing

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#241]
![screen shot 2017-11-22 at 10 40 15 am](https://user-images.githubusercontent.com/31738798/33135828-8a7c32ba-cf71-11e7-9d5e-a536d5cda419.png)

When resized to a more mobile sizing (362 x 858) the three cards look abnormally small.

**Comment by ekfuhrmann** [comment]
This is correct. We don't have different image sets for mobile, so the image just scales down in order to preserve the structure.
