### ISSUE TITLE
B Line Case Study: Testimonial 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#242]
![screen shot 2017-11-22 at 10 42 46 am](https://user-images.githubusercontent.com/31738798/33135959-f59a1706-cf71-11e7-8191-526e555a33c7.png)

Not sure if my eyes are playing tricks on me but this font (on the left) looked maybe slightly different or heavier than rest of the page. Also should the font on the right be the serif font?

**Comment by ekfuhrmann** [comment]
This is consistent with all testimonials.
