### ISSUE TITLE
Congressional Digital Service Case Study: How it works 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#246]
![screen shot 2017-11-22 at 11 00 27 am](https://user-images.githubusercontent.com/31738798/33136901-69945c3c-cf74-11e7-8041-3cafcd433ff2.png)
 There are no animations for this section whereas all other sections are animated - is this supposed to actually have some sort of animation?

**Comment by ekfuhrmann** [comment]
It is not.
