### ISSUE TITLE
Congressional Digital Service: Intro Page 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#247]
![screen shot 2017-11-22 at 11 03 05 am](https://user-images.githubusercontent.com/31738798/33137019-c7fe0c82-cf74-11e7-896a-406047917b4b.png)

When I resized to the mobile-ish size and refreshed so that i could start reviewing the entire page at the mobile size - the intro page animations don't work, even when i refreshed multiple times.

**Comment by ekfuhrmann** [comment]
This was a mistake on my part. When I added the intro animation, I had it only fire off on viewports that were larger than mobile. This mean mobile was stuck with a transparent intro. I fixed this in my latest build, so ignore this issue elsewhere.
