### ISSUE TITLE
Congressional Digital Service: How it Works 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#248]
![screen shot 2017-11-22 at 11 07 07 am](https://user-images.githubusercontent.com/31738798/33137225-5f1a9054-cf75-11e7-934d-a67aede25c75.png)

When resized to a smaller, more mobile-ish size, this section becomes super small

**Comment by ekfuhrmann** [comment]
Similar to #241, there is no mobile display for this section, so it scales down while maintaining position.
