### ISSUE TITLE
City Health Case Study: Sample city badges 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#252]
![screen shot 2017-11-22 at 1 24 49 pm](https://user-images.githubusercontent.com/31738798/33143649-8b8985f6-cf88-11e7-8506-c223302fab46.png)

not sure but are these supposed to show up vertically when in the mobile view? When resized to the mobile size, they appear quite small.

**Comment by ekfuhrmann** [comment]
like #241, we do not have a mobile display for this. These are being animated in as a part of an image, rather than individual elements on a traditional site, so there is no change to be done here.
