### ISSUE TITLE
Collaborate Case Study: Images

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#255]
![screen shot 2017-11-22 at 1 40 27 pm](https://user-images.githubusercontent.com/31738798/33144362-c39bbfde-cf8a-11e7-8978-26ccb34ff334.png)

![screen shot 2017-11-22 at 1 46 57 pm](https://user-images.githubusercontent.com/31738798/33144641-be4ef270-cf8b-11e7-95c7-74438c819d04.png)

 Poor image quality

**Comment by ekfuhrmann** [comment]
I've spoken to the designers about this, unfortunately we do not have any better images to work with from this event.
