### ISSUE TITLE
Collaborate: Ribbons bottom of page 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#258]
![screen shot 2017-11-22 at 1 52 42 pm](https://user-images.githubusercontent.com/31738798/33144851-70857a22-cf8c-11e7-9371-8a6154bdffe2.png)

Those three ribbons - is there supposed to be some sort of animation for them? also the image quality is not so good

**Comment by ekfuhrmann** [comment]
No animation to these, and like #255, these are the best images we have of this event.
