### ISSUE TITLE
Collaborate: Testimonial

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#259]
![screen shot 2017-11-22 at 1 54 08 pm](https://user-images.githubusercontent.com/31738798/33144908-a0cbbb24-cf8c-11e7-935c-e0dc23168910.png)

This quote does not 100% align with the testimonial on the right, nor is the left hand quote accurate with relation to the right hand testimonial.

**Comment by ekfuhrmann** [comment]
Changed from a 2-col quote to a single column (no callout).
