### ISSUE TITLE
Case Studies Testimonials

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#260]
![screen shot 2017-11-22 at 1 56 55 pm](https://user-images.githubusercontent.com/31738798/33145152-550d3004-cf8d-11e7-9383-8b28a177d9c9.png)

In many of the case studies, the left hand quote and the right hand testimonial (@ bottom of page) do not top align. The above is an example from CityHealth, but nonetheless - this persists throughout most of the case studies.

**Comment by ekfuhrmann** [comment]
The left quote is center aligned to the right based on relation to the container it is in. The padding top and bottom is equidistant. The long quote on the right height includes the "quote" icon. When you take the icon, long quote text, and author name into consideration, the callout quote on the left is balanced.
