### ISSUE TITLE
Collaborate: Know where you are 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#263]
![screen shot 2017-11-22 at 4 48 43 pm](https://user-images.githubusercontent.com/31738798/33151201-17328c80-cfa5-11e7-93ad-abfb927cefe4.png)

Do you think these images are too small?

**Comment by ekfuhrmann** [comment]
The alternative to scaling these images, is to either have mobile specific imagery or scale. We have opted to scale the images down.
