### ISSUE TITLE
Discovery Case Study: Intro section 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#264]
![screen shot 2017-11-22 at 4 52 48 pm](https://user-images.githubusercontent.com/31738798/33151344-b729ea9e-cfa5-11e7-8617-5018f60dcc69.png)

I know you said not to look for copy issues, but.... this should say "We designed and built the debut of _a_ website showing..."

**Comment by ekfuhrmann** [comment]
Nice catch
