### ISSUE TITLE
Stretch Case Study: Copy Change 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#267]
![screen shot 2017-11-29 at 1 23 42 pm](https://user-images.githubusercontent.com/31738798/33391940-94c86634-d508-11e7-980a-a767c798af9e.png)

I don't know part of the sentence is just a bit awkwardly worded and there's an extra "a" before "live": maybe it should say "We reimagined the Stretch brand, and launched a new live online viewing experience, a CMS for producers, and a behind-the-scenes support system." or "We reimagined the Stretch brand - we launched a new live online viewing experience, a CMS for producers, and a support system behind the scenes."(or "behind-the-scenes support system")

**Comment by jennabillingsley** [comment]
@ekfuhrmann change this copy to: We reimagined the Stretch brand, and launched a new live online viewing experience, a CMS for producers, and a behind-the-scenes support system.
