### ISSUE TITLE
Stretch Streaming Media: Some animations 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#268]
<img width="1528" alt="screen shot 2017-11-29 at 1 38 24 pm" src="https://user-images.githubusercontent.com/31738798/33392639-a516981a-d50a-11e7-9876-1dd14b62f595.png">

<img width="1465" alt="screen shot 2017-11-29 at 1 45 17 pm" src="https://user-images.githubusercontent.com/31738798/33392954-95607264-d50b-11e7-95d1-6415bf059055.png">

Should the animation be slightly slower? And should both portions be in syn?

**Comment by ekfuhrmann** [comment]
The speed of the animations are consistent across all case studies. To slow them down here, we'd need to decide to have them slowed down everywhere else.

I'm of the opinion that these animations should not be a focal point of the case studies, and by slowing down the animation will only make them more apparent then they ought to be within this context.

In regards to the image being out-of-sync with the text, that is true, but hard to avoid. The way it works is based on how much of the block is within the viewport. The text and images are both variable heights depending on section, so there is no good way to have them sync. I don't think this is a large enough of an issue to require further dev time. Most normal use cases will be a user scrolling down naturally with content appearing at certain scroll heights. If text is not there, the user will scroll and text will then appear.
