### ISSUE TITLE
Stretch Streaming Media: For Viewers 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#269]
<img width="1330" alt="screen shot 2017-11-29 at 1 40 16 pm" src="https://user-images.githubusercontent.com/31738798/33392725-d9454cee-d50a-11e7-8da5-648038c96596.png">

Should the animations be incremented like they are currently? or should they both happen at the same time? (the text and the image slide)

**Comment by ekfuhrmann** [comment]
The animations depend on how much of the element block, whether it be text or image, is in viewport.  See #268 

The behavior is working as intended right now.
