### ISSUE TITLE
Stretch Streaming Media: This year-long engagement...

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#270]
<img width="661" alt="screen shot 2017-11-29 at 1 41 42 pm" src="https://user-images.githubusercontent.com/31738798/33392800-1db51f80-d50b-11e7-945d-8ede94a175ae.png">

This is super specific, but is there a reason why there is a period here and not in the captions below? and vice versa? A period makes sense in the "we reimagined..." sentence, but for this case why is there a period?

**Comment by jennabillingsley** [comment]
@ekfuhrmann remove the period
