### ISSUE TITLE
Stretch Streaming Media: For techs - loading 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#271]
<img width="1502" alt="screen shot 2017-11-29 at 1 52 56 pm" src="https://user-images.githubusercontent.com/31738798/33393279-b1f44594-d50c-11e7-8ed3-b13c2729dd5c.png">

When this page loads it is slightly delayed and the background loads oddly - like have the screen will be a little dulled out for like 1 sec

**Comment by ekfuhrmann** [comment]
Sections now have the proper height regardless of whether or not the image has finished loading. I was unable to recreate this specific bug, but the fixed I have applied should prevent this from occurring again.
