### ISSUE TITLE
Stretch The Brand: we set out....

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#273]
<img width="1556" alt="screen shot 2017-11-29 at 2 56 45 pm" src="https://user-images.githubusercontent.com/31738798/33396101-8d2340ea-d515-11e7-904f-56b48fa03b6f.png">

I see why "Live Streaming" is capitalized, but it's a little awkward and i don't think the capitalization is necessary

**Comment by jennabillingsley** [comment]
Can remove the capitalization on "Live Streaming".  @ekfuhrmann check the contrast on the green and white text. That green may have to be darkened slightly.

**Comment by ekfuhrmann** [comment]
I changed the color to `#1CCCB6` which is the brand green we used on the actual Stretch site. It has slightly better contrast.
