### ISSUE TITLE
Stretch streaming media: 'the portal' image 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#275]
<img width="410" alt="screen shot 2017-12-06 at 10 33 13 am" src="https://user-images.githubusercontent.com/31738798/33669678-21f56e4a-da71-11e7-81c3-f7c0140cda51.png">

This image looks narrow.

**Comment by ekfuhrmann** [comment]
Agreed. 

@theseangoodwin this may be a result of not using the same frame in the designs as we do on the site. -- See #228
