### ISSUE TITLE
Stretch Brand Case Study: Logo 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#277]
<img width="703" alt="screen shot 2017-12-06 at 1 10 10 pm" src="https://user-images.githubusercontent.com/31738798/33677455-d3aa1504-da86-11e7-9335-2653cd950638.png">

Is it just me or is the right copy not aligned?

**Comment by ekfuhrmann** [comment]
@theastralj designed this animation. I'm just serving up the video file.

**Comment by theastralj** [comment]
The right copy is aligned per the intent of the designers. Closing this issue
