### ISSUE TITLE
Stretch Brand Case Study: Fighting Fires 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#280]
<img width="652" alt="screen shot 2017-12-06 at 1 17 43 pm" src="https://user-images.githubusercontent.com/31738798/33677779-de9335c6-da87-11e7-8432-157128aa50be.png">

Is the R in the email supposed to be capitalized?

**Comment by jennabillingsley** [comment]
I'm ok with it being capitalized

**Comment by ekfuhrmann** [comment]
Fun fact, in an email address you capitalize any letters you want, as well as add periods (`.`) anywhere you want without it affecting address.

So `test@gmail.com` is the same as `t.E.s.T@gmail.com`!
