### ISSUE TITLE
Stretch Portal Case Study: Mobile-first 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#285]
<img width="434" alt="screen shot 2017-12-06 at 1 29 21 pm" src="https://user-images.githubusercontent.com/31738798/33678388-9333ff28-da89-11e7-905e-00207e6eea26.png">

Is that small rectangle protruding from the phone supposed to be the side buttons on an iphone? I don't know they're kinda distracting and dont look like part of a phone - this isn't a huge issue or anything though.

**Comment by ekfuhrmann** [comment]
Related to #228

**Comment by ekfuhrmann** [comment]
The tab on the phone was intended for the original frame design. The updated frames will look cleaner once completed (#228)
