### ISSUE TITLE
Stretch Portal Case Study: Make it tangible  

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#286]
<img width="400" alt="screen shot 2017-12-06 at 1 32 33 pm" src="https://user-images.githubusercontent.com/31738798/33678511-efb75df8-da89-11e7-952a-8a0e397cdb49.png">

not sure if "intuitive way" is the right way to put it? or at least the word "way" could be replaced.

**Comment by jennabillingsley** [comment]
Replace with:
We found that users instinctively had an idea of what an 'event' was, so we turned this mental concept into an intuitive way to get around.
