### ISSUE TITLE
Stretch Portal Case Study: For communities that scale 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#287]
<img width="1178" alt="screen shot 2017-12-06 at 1 36 09 pm" src="https://user-images.githubusercontent.com/31738798/33678696-7a941bdc-da8a-11e7-9952-d3804b1a398a.png">

Are these images supposed to be larger? 

The front image was delayed in loading compared to the blurb and the back image (bowling green one)

**Comment by ekfuhrmann** [comment]
They stagger reveal, though you may have seen it take longer than expected due to lazy loading. I've changed the threshold for lazy loading now so it should be a bit more seamless.
