### ISSUE TITLE
Stretch CMS Case study: stage image 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#292]
<img width="1338" alt="screen shot 2017-12-06 at 1 48 50 pm" src="https://user-images.githubusercontent.com/31738798/33679259-3bd6e1e8-da8c-11e7-9e46-a6bd72b1806b.png">

Is there supposed to be content here on the left side? it _looks_ like there is supposed to be?

**Comment by ekfuhrmann** [comment]
There is not, though this was used on the site with copy accompanying it. In this instance it was just an image break, but something to consider for the designers.

**Comment by jennabillingsley** [comment]
It should not have copy and it is misleading. @ekfuhrmann change the height of this to be much shorter so it feels like an interstitial screen.

**Comment by ekfuhrmann** [comment]
I've now halved the height of this section to be `37.5vh` as opposed to `75vh`.
