### ISSUE TITLE
Stretch System Case Study: Fighting Fires 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#297]
<img width="1318" alt="screen shot 2017-12-06 at 1 57 21 pm" src="https://user-images.githubusercontent.com/31738798/33679697-6bca655e-da8d-11e7-9ec9-5953bc7dd483.png">

This title is previously used in the "brand" case study section --> is it ok that they have the same titles?

**Comment by theseangoodwin** [comment]
Good catch, this is the correct content on this page. The brand page has incorrect content ('Fighting Fires' and the paragraph below do not relate to business cards).

<img width="1298" alt="screen shot 2018-01-25 at 5 55 37 pm" src="https://user-images.githubusercontent.com/25349814/35416950-2fbede6c-01f9-11e8-8dee-b822ffb398b4.png">

**Comment by theseangoodwin** [comment]
New content:

Reaching all Audiences

Stretch needed marketing collateral that could reach beyond digital to connect in the real-world. 

We extended the brand to marketing materials that gave the Stretch team the ability to showcase their brand for every aspect of their day-to-day lives, including business cards, presentations, trade shows and more.

cc @ekfuhrmann

**Comment by ekfuhrmann** [comment]
Updated copy
