### ISSUE TITLE
Stretch System Case Study: image of guy on computer 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#299]
<img width="1209" alt="screen shot 2017-12-06 at 1 59 58 pm" src="https://user-images.githubusercontent.com/31738798/33679805-c30a1a6c-da8d-11e7-93ee-464ebc4e7f6c.png">

This _looks_ like there should be content there because it's such a vertically wide image.

**Comment by ekfuhrmann** [comment]
Similar to #292

**Comment by theseangoodwin** [comment]
We're just looking at the system in context here. We could possibly make this shorter by ~30% to ensure people scroll through. Alternatively, we could remove the wave. Will defer to @jennabillingsley on this.

**Comment by ekfuhrmann** [comment]
I'm going to treat this the same as #292 which @jennabillingsley provided feedback on.
