### ISSUE TITLE
Stretch Portal Case Study: Visual Artifacts in Footer Hero

### ISSUE THREAD

**Issue by theastralj** [BraveUX/braveux#306]
Some odd shadowing and white splotches in the top of edge of the footer hero:

![image](https://user-images.githubusercontent.com/1764989/33682247-e0f1ed78-da94-11e7-8699-a6ce9a0fa4e7.png)

**Comment by ekfuhrmann** [comment]
This actually is due to the image. I cropped out the portions which were causing that artifacting.
