### ISSUE TITLE
Stretch CMS Case Study: Low Image Quality

### ISSUE THREAD

**Issue by theastralj** [BraveUX/braveux#307]
The quality on this Performance Stats screenshot seems unusually low compared to the rest of the case study: 

![image](https://user-images.githubusercontent.com/1764989/33682313-14877e32-da95-11e7-9900-7e5e2f9037f3.png)

**Comment by ekfuhrmann** [comment]
I've bumped up the quality of images across the site from "medium" to "high" in the jpeg compression task.

In addition, I took this asset out of sketch again, making it 2x it's default size. Truth be told, it still hasn't scaled down great leaving aliasing, but it has been improved.
