### ISSUE TITLE
Stretch repeating theme color

### ISSUE THREAD

**Issue by ekfuhrmann** [BraveUX/braveux#315]
We use the same base color (Green) for both the Stretch landing page and the `The Brand` page. Since every subpage has its own related theme color, I think it would look better if one of these made use of a different brand color, such as `Red` since it is not used elsewhere.

https://braveux.com/work/stretch/:
![image.png](https://images.zenhubusercontent.com/5900aa4d51aa2c30577c8797/3c227f3b-52fb-45c1-a778-e8d4782d3dad)

https://braveux.com/work/stretch/brand:
![image.png](https://images.zenhubusercontent.com/5900aa4d51aa2c30577c8797/cceb71a8-2bba-444d-953a-cd4c85bdcbc1)

**Comment by jennabillingsley** [comment]
@ekfuhrmann Leave as is. The core brand color is green, which makes it the appropriate choice for both sections. In this case it's clarity over consistency.
