### ISSUE TITLE
iConstituent Case Study: color of intro caption copy  

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#318]
<img width="901" alt="screen shot 2018-02-07 at 9 56 47 am" src="https://user-images.githubusercontent.com/31738798/35923064-3f1e3580-0bed-11e8-8d15-6739f62bfd87.png">

Is there any way we could adjust the white of the text to make it easier on the eyes a bit?

**Comment by jennabillingsley** [comment]
@ekfuhrmann need the blue to be darkened slightly to make the white easier to see

**Comment by ekfuhrmann** [comment]
Darkened the blue slightly for better contrast
