### ISSUE TITLE
iConstituent Case Study: Signed Sealed Delivered image 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#323]
<img width="1323" alt="screen shot 2018-02-07 at 11 59 37 am" src="https://user-images.githubusercontent.com/31738798/35929852-76f94038-0bfe-11e8-9108-ac6e6dbf487a.png">

does the bottom third of the image need to be there? Looks kinda long

**Comment by ekfuhrmann** [comment]
I think it balances out the sidebar nicer and gives you a better idea that you are building a document as opposed to some sort of web element block.
