### ISSUE TITLE
iConstituent: Page divider image under Signed, Sealed, Delivered 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#324]
<img width="1573" alt="screen shot 2018-02-07 at 3 55 55 pm" src="https://user-images.githubusercontent.com/31738798/35941182-69778fb6-0c1f-11e8-8124-148e16c8ea90.png">

are the yellow bubbles supposed to be above the underlined portions? because they kinda look like they're floating. Should the bubbles also be slightly angled so that it makes sense with the angled page of text it's sitting on? 

also, the animation looks cool, but it's kinda awkward that the red marking on the bottom left is slightly cut off.

**Comment by ekfuhrmann** [comment]
This was developed to the design spec. The cropped circle was intentional and teh yellow comments were not located above the circles in the design.

@jennabillingsley I see no issue with this section and it is true to Jessie's design, but let me know if you think we should update it.

**Comment by jessiekam** [comment]
In the product, leaving a comment is different from drawing on a document so the comment bubbles have no relation to the underlines. Let's keep as is.
