### ISSUE TITLE
iConstituent Case Study: A quick show of hands content 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#325]
<img width="1357" alt="screen shot 2018-02-07 at 4 17 46 pm" src="https://user-images.githubusercontent.com/31738798/35942075-80a5b2fa-0c22-11e8-9d76-6336343f9099.png">
Since we talk about "batch views" here, shouldn't we have an image of a batch view?

**Comment by theseangoodwin** [comment]
@jessiekam Great question. I assume there's a reason we don't have one.

**Comment by jessiekam** [comment]
This is fine. The actual batch view that goes along with these screens is just another table so I'd rather show what we have here.
