### ISSUE TITLE
iConstituent Case Study: A Key to the City images 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#328]
<img width="1065" alt="screen shot 2018-02-07 at 4 31 31 pm" src="https://user-images.githubusercontent.com/31738798/35942666-69d094e4-0c24-11e8-86e3-a97027166ac8.png">

<img width="1420" alt="screen shot 2018-02-07 at 4 36 29 pm" src="https://user-images.githubusercontent.com/31738798/35944167-863fd2c0-0c29-11e8-9488-c2ea674fe8f3.png">

- the right-most image's bottom border is faded but the other two's are not. 
- I feel like these images aren't necessarily related to the navigation structure like the description is inferring.

**Comment by jennabillingsley** [comment]
The fade is because the content is scrolling within the window, so ok with that.  Also ok with the images depicted even if not exactly showing the navigation. It shows the other content.
