### ISSUE TITLE
iConstituent Case Study: Fade above Testimonial 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#329]
<img width="1435" alt="screen shot 2018-02-07 at 4 33 55 pm" src="https://user-images.githubusercontent.com/31738798/35942759-c58c0502-0c24-11e8-92a0-cb7ed08fa695.png">

Since the left side of the testimonial is white and the lower part of the image above it is so faded, it looks like they blend together. Should the image be slightly less faded?

**Comment by theseangoodwin** [comment]
New testimonial layout solves this problem.
