### ISSUE TITLE
gCrit: Conversation engaged image 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#331]
<img width="666" alt="screen shot 2018-02-07 at 5 36 41 pm" src="https://user-images.githubusercontent.com/31738798/35945239-818fbee4-0c2d-11e8-98c7-ec92fa576e81.png">

Upper right side border is misaligned with the browser header

**Comment by ekfuhrmann** [comment]
This was annoying, Sometimes the image is not a perfectly whole pixel value, and different browsers render these ratio pixels differently (some round up, others down). I tried to resolve this by trimming a pixel off the frame, which resolved most instances in chrome, but didn't work nearly as consistently in Firefox.

I've changed it now that I actually have the frame full size `100%` and then the image under it `calc(100% + 1px)`.  This will always force the image to round up as I am already adding a pixel to it.  Now knowing that the image will always be at least `1px` larger than the frame, I have the frame hide the overflow and trim the image to size perfectly to that of the frame.

I think this will fix all further instances of this issue.
