### ISSUE TITLE
gCrit: down to the wire mobile image 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#332]
<img width="436" alt="screen shot 2018-02-07 at 5 40 21 pm" src="https://user-images.githubusercontent.com/31738798/35945371-00cc9a88-0c2e-11e8-99df-d3b08ca29297.png">

bottom nav looks kinda strange - not sure if it's supposed to look like this

**Comment by ekfuhrmann** [comment]
That's actually part of the iOS design language making use of a frosted-glass type effect.

![image](https://user-images.githubusercontent.com/8878152/36105997-16c58840-0fe4-11e8-8cef-93067c27957c.png)
