### ISSUE TITLE
gCrit Case Study: mobile comments image after "Conversation engaged" section 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#334]
<img width="1501" alt="screen shot 2018-02-07 at 5 48 05 pm" src="https://user-images.githubusercontent.com/31738798/35945720-267c0f88-0c2f-11e8-8a35-846bea67df90.png">

- the mobile image looks a little too high up
- is that the usual mobile border we use? idk the button edges look a bit too sharp and the top part of the design is cut off (time, battery life etc.) by the border (same thing happens on "Down to the Wire" page and "From Pocket to Drafting Table" tablet and mobile images)

**Comment by ekfuhrmann** [comment]
Whoops, I screwed up with the class name in this instance. It should fill the container with some padding along the sides and top now.

Regarding the frame cropping some of the copy, that should be resolved when we push out updated mobile frames that @theseangoodwin will most likely get to tomorrow (2/13)!
