### ISSUE TITLE
gCrit: from picket to drafting table 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#336]
<img width="1296" alt="screen shot 2018-02-07 at 5 57 51 pm" src="https://user-images.githubusercontent.com/31738798/35946093-7af3c5d2-0c30-11e8-8f14-47bb5ce08d1f.png">

- same comment as previous issue (mobile & tablet screens are cut off by border) 
- The mobile/tablet border have an additional darker grey border- i know that these are devices themselves and the web browser is not a device, but would it look more cohesive if they all didn't have the dark grey border?

**Comment by ekfuhrmann** [comment]
Frame update should fix this in the future.
