### ISSUE TITLE
DL Case Study: Chain Reactions animation 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#342]
Appeared to be a little staticky (e
<img width="1434" alt="screen shot 2018-02-08 at 9 45 53 am" src="https://user-images.githubusercontent.com/31738798/35978893-df940a18-0cb4-11e8-9fc8-768d679792d6.png">
ven when I refreshed)

**Comment by ekfuhrmann** [comment]
Similar to #326 - Will vary based on hardware/processor/internet
