### ISSUE TITLE
DL Case Study: Vaults of Inspiration copy & animation 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#343]
<img width="831" alt="screen shot 2018-02-08 at 9 50 10 am" src="https://user-images.githubusercontent.com/31738798/35979184-b3041348-0cb5-11e8-8330-734864a093eb.png">

"Users might not want to just wander. For users hunting for a big idea, powerful search functions bring immediate inspiration, so that users don't lose creative momentum."
Copy:
- change "users" to "they" in last clause. 

Animation:
- the animation for the image is delayed

**Comment by ekfuhrmann** [comment]
Updated copy and image threshold for animating is now sooner.
