### ISSUE TITLE
DL Case study: built to inspire animation 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#346]
The roll-up seemed to be a little staticky & delayed 
<img width="1344" alt="screen shot 2018-02-08 at 10 07 08 am" src="https://user-images.githubusercontent.com/31738798/35980153-ff6fe840-0cb7-11e8-832c-fd1050431075.png">

**Comment by ekfuhrmann** [comment]
It uses the same animation timing as the other sections. This could be a case of your computer just rendering the animation slower than normal, but nothing in the code should delay it from appearing in relation to other sections with the same animation.
