### ISSUE TITLE
DL Case Study: Border Streaks

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#348]
Not sure if I'm seeing things, but like gCrit some of the areas bordering the images (where the drop shadows are) are looking slightly streaky?
<img width="372" alt="screen shot 2018-02-08 at 10 13 32 am" src="https://user-images.githubusercontent.com/31738798/35980509-db22f4ea-0cb8-11e8-921c-e3a3afc7371f.png">

**Comment by ekfuhrmann** [comment]
This is some more banding -- see #333, #339
