### ISSUE TITLE
MOBILE iConstituent Case Study: Solution/Scope Roll up  

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#349]
On iPhone X safari: took a little bit of time for the solution/scope to roll up
<img width="526" alt="screen shot 2018-02-08 at 10 22 53 am" src="https://user-images.githubusercontent.com/31738798/35980996-2b71614c-0cba-11e8-9d93-deff2602986d.png">

**Comment by ekfuhrmann** [comment]
The emulator can have issues rendering animation. The class is the same as used throughout.
