### ISSUE TITLE
MOBILE iConstituent Case Study: a key to the city animation 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#352]
<img width="614" alt="screen shot 2018-02-08 at 10 30 15 am" src="https://user-images.githubusercontent.com/31738798/35981376-1a9c6942-0cbb-11e8-934b-f8fbe7a4ecfd.png">

iphone x safari 
Seemed a little broken when it animated and the last component of the animation (last thing to roll up) flashed a few times - maybe this was just because i was on browser stack through 

Also the drop shadows look a little intense in this view (these drop shadows could be the same ones we have in the desktop version, but here they're more pronounced)

**Comment by ekfuhrmann** [comment]
Yeah don't use browser stack as a judge of animation load quality. It's a virtual machine so animations do not render smoothly ever. The key thing to watch for is content placement and that content is rendering properly.
