### ISSUE TITLE
MOBILE gCrit Case Study: loading after the intro 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#357]
<img width="424" alt="screen shot 2018-02-08 at 10 55 25 am" src="https://user-images.githubusercontent.com/31738798/35982770-950d995a-0cbe-11e8-8790-94840d194dce.png">
galaxy chrome 

The challenge/solution area only loads once i'm over half way up the screen

**Comment by ekfuhrmann** [comment]
I've increased the threshold for this to reveal
