### ISSUE TITLE
MOBILE gCrit Case Study: Breathtaking views image 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#360]
<img width="424" alt="screen shot 2018-02-08 at 11 01 51 am" src="https://user-images.githubusercontent.com/31738798/35983205-8bed8d3e-0cbf-11e8-8768-6962eeab0261.png">

galaxy chrome 

drop shadow looks streaky and then the top browser header looks thicker than what is in the desktop version

**Comment by ekfuhrmann** [comment]
Duplicate #333
