### ISSUE TITLE
MOBILE gcrit case study: from pocket to drafting table 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#362]
<img width="414" alt="screen shot 2018-02-08 at 11 09 31 am" src="https://user-images.githubusercontent.com/31738798/35983714-97047fce-0cc0-11e8-9ebf-13c4fc2090d4.png">

galaxy chrome 

Images look v proportionally small

**Comment by ekfuhrmann** [comment]
Duplicate #350
