### ISSUE TITLE
MOBILE gCrit Case Study: Disproportional Size  

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#364]
<img width="459" alt="screen shot 2018-02-08 at 12 47 55 pm" src="https://user-images.githubusercontent.com/31738798/35989095-4d4c99ee-0cce-11e8-8115-507d9893ea26.png">

<img width="494" alt="screen shot 2018-02-08 at 12 51 20 pm" src="https://user-images.githubusercontent.com/31738798/35989285-caea0120-0cce-11e8-8759-761f65acfc43.png">

iphone x safari

appears small compared to other images

**Comment by ekfuhrmann** [comment]
Duplicate #350
