### ISSUE TITLE
MOBILE DL Case study: Chain Reactions 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#366]
<img width="496" alt="screen shot 2018-02-08 at 12 57 22 pm" src="https://user-images.githubusercontent.com/31738798/35989660-c17efafe-0ccf-11e8-9b28-cfc37f443b74.png">

Drop shadow looks intense and there's this random blue strip on the left; lower left image looks cut off

**Comment by ekfuhrmann** [comment]
Blue strip is emulator jankiness - not there normally. Drop shadow is same as in desktop.
