### ISSUE TITLE
MOBILE DL Case Study: Built to inspire dropshadow 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#367]
<img width="331" alt="screen shot 2018-02-08 at 1 43 25 pm" src="https://user-images.githubusercontent.com/31738798/35991740-1a4ca054-0cd6-11e8-8ee5-7fe871197a1a.png">

top edge drop shadow looks intense

<img width="572" alt="screen shot 2018-02-08 at 1 47 42 pm" src="https://user-images.githubusercontent.com/31738798/35991905-add8780c-0cd6-11e8-888a-fb778a670c3a.png">

same thing in the "chain reactions" section ^

**Comment by ekfuhrmann** [comment]
These both use the same drop-shadow as the rest of our case studies. It looks more pronounced perhaps due to the lighter background color.

I personally do not think it looks too strong or out of place, but going to link this issue up with #358
