### ISSUE TITLE
MOBILE DL Case Study: Page divider "the future has arrived...." 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#368]
<img width="423" alt="screen shot 2018-02-08 at 1 45 09 pm" src="https://user-images.githubusercontent.com/31738798/35991789-4b145e66-0cd6-11e8-996e-e09c8a0b2ef3.png">
the lower right hand square directly below the "the future has arrived ..." square: the left edge seems to have a whitish border

**Comment by ekfuhrmann** [comment]
This is correct, that's actually how the building looks without tint. Compare it to the strip of building above the "This direction is not only..." tile.

![image](https://user-images.githubusercontent.com/8878152/36113404-b12ea414-0ffa-11e8-979b-a6c5344b087f.png)
