### ISSUE TITLE
Animate plot graph

### ISSUE THREAD

**Issue by ekfuhrmann** [BraveUX/braveux#370]
@theseangoodwin I tried to do this with layering and loading content, but it just didn't come together great with the mouse and timing, so I think this would be much better served as an after-effects animation.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/8878152/36047151-44038a24-0da9-11e8-8944-3e68610bb43f.png">

On hover:
* The plot blip should scale up larger and outlined
* The line itself should add a drop shadow
* The tooltip should then perhaps move up and fade in to the right of the cursor
* Fade in the background numbers.

**Comment by theseangoodwin** [comment]
Here is a folder containing an MP4 and Webm of this animation:

https://www.dropbox.com/sh/o1nyz0g6tjt7hlv/AAADTDm_JmUWJ4p1FHxmPzx2a?dl=0
