### ISSUE TITLE
ROKT Case Study: Title/Subtitle

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#371]
<img width="595" alt="screen shot 2018-02-13 at 9 47 56 am" src="https://user-images.githubusercontent.com/31738798/36155721-1b5f187a-10a3-11e8-8be2-a4a7d4038cf5.png">

"E" in ecommerce should be lowercase --> *w/ edits: "eCommerce Advertising Platform"* 

Also, i dont know, maybe this is just subjective but "Solving the internet's problems with ads" doesn't quite make much sense to me (it's a headline, so i know it's supposed to be vague and it isn't always logical/rational) because "internet's problems" is just so so so vague and general and I'm not quite sure what internet problems Rokt solves other than for advertisers/"publishers" and vulnerable consumers.

**Comment by jennabillingsley** [comment]
@gabrielataginya how about "Creating a seamless marketplace for ads"

**Comment by theastralj** [comment]
- It should read "eCommerce"

- The core reason why Rokt works is that it is still able to deliver ads (a necessary evil) in a format that doesn't piss users off - none of the analytics, marketplace is effective without that core part working first, so, I'm going to have @ekfuhrmann change it to:

'Ads that work for everyone' - play on work as in acceptable and work as in productive
