### ISSUE TITLE
Rokt Case Study: intro KPI image 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#372]
<img width="995" alt="screen shot 2018-02-13 at 9 59 01 am" src="https://user-images.githubusercontent.com/31738798/36156287-8c99af86-10a4-11e8-93a6-ce9f40b88910.png">

It looks like these numbers aren't purposefully cut off. I could see this purposefully being designed that way though, but I think it looks like they shouldn't be cut off/a mistake - that's just my subjective opinion though and others might not feel that it looks like a mistake.

**Comment by jennabillingsley** [comment]
@gabrielataginya is correct. This should not be cut off. Please reference design file.
