### ISSUE TITLE
Rokt Case Study: How It Works 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#373]
![screen shot 2018-02-13 at 12 56 54 pm](https://user-images.githubusercontent.com/31738798/36165395-6f4b25d6-10bd-11e8-9e0f-6de4516732b8.png)

Smaller screen: 

<img width="1312" alt="screen shot 2018-02-13 at 1 59 12 pm" src="https://user-images.githubusercontent.com/31738798/36168165-235c90d4-10c6-11e8-9d4d-1740bacc4161.png">

A) FIrst, i like that we describe how Rokt works, but I think we need to somehow hint that this is how ROKT works CURRENTLY because it kinda leads the user to believe that this was Brave's work. 

B) Step 2: 
In step 2, instead of "Uber" it should be "Hotels.com"
In step 2, instead of "Offered" it should be "Offer"
In step 2, instead of "discounted ride" to "discounted hotel booking". 
*w/ edits: Rokt finds a relevant Advertiser (like Hotels.com) to show the customer an offer tailored to them, like a discounted hotel booking.* 

OR we could just change the step 2 image to an image of an Uber ad because keeping the Uber example is a little more intuitive to the concert ticket example. 

C) Step 3: 
- I feel like we should maybe specify how the ads are sensibly placed because we mention that there are ads that are distracting  in the middle of a shopping experience. Maybe add "after a transaction","at the end of their interaction with the site" after "relevant offers" 

*w/ potential edits: Instead of distracting ads in the middle of the shopping experience, customers get optional, always-relevant offers sensibly placed after their transaction, meaning everybody wins.*
- the dropshadow in step three below top bar (w/ email count etc.) looks very intense. 

D) In the smaller screen, the numbers are recognizable (1, 2, 3), but they look like they're a liiiiiiittttle too cut off

**Comment by jennabillingsley** [comment]
This is supposed to be a high-level intro to the concept of campaigns and placements, and the images are from the Rokt website so we unfortunately can't change them out.  :( 

@ekfuhrmann Adjusted the copy in the file.
