### ISSUE TITLE
Rokt Case Study: Context of Current Rokt Platform

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#374]
Would it be relevant to somehow mention (not necessarily show) Rokt's previous platform and its core issue for some context? Because re-reading what we've identified as the challenge --> the "complex, new way of thinking", to me, sounds like that's referring to our new mental model and not the Rokt "method". Maybe it's because we use the word "new"? which leads me to believe that the current Rokt platform is a new way of thinking. 

<img width="407" alt="screen shot 2018-02-13 at 1 35 46 pm" src="https://user-images.githubusercontent.com/31738798/36167140-d43ba132-10c2-11e8-9412-92316e052052.png">

**Comment by jennabillingsley** [comment]
Would change the copy to: A lot of experience, sophistication and nuance has gone into Rokt's methods for serving content users actually care about. How can we help users efficiently transition into this new way of thinking?
