### ISSUE TITLE
Rokt Case Study: higher resolution 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#375]
1. Getting the band back together divider
<img width="1423" alt="screen shot 2018-02-13 at 1 37 39 pm" src="https://user-images.githubusercontent.com/31738798/36167230-1b8d5c38-10c3-11e8-9b40-3bb02e45ba2b.png">

- I feel like this divider would look better if it were in higher resolution

- Also why do we have the light grey number in the background? ~also, should there be an animation?~ (see @ekfuhrmann comment below)

2.  Read to go live image 
![screen shot 2018-02-13 at 2 18 39 pm](https://user-images.githubusercontent.com/31738798/36168974-dfc39cd4-10c8-11e8-9135-77323a27dfc7.png)

3. A pulse on the market from anywhere image
![screen shot 2018-02-13 at 2 21 39 pm](https://user-images.githubusercontent.com/31738798/36169132-58e9631e-10c9-11e8-8d4b-53e0fc0744e4.png)

4. 
![screen shot 2018-02-13 at 2 27 06 pm](https://user-images.githubusercontent.com/31738798/36169529-76adfc7e-10ca-11e8-9c2f-f756100f3baa.png)

5. Getting the band back together 
![screen shot 2018-02-13 at 2 37 06 pm](https://user-images.githubusercontent.com/31738798/36169844-6c86cf2c-10cb-11e8-8dcc-7910c177473b.png)

**Comment by ekfuhrmann** [comment]
Graph animation has been logged in #370

**Comment by jennabillingsley** [comment]
@ekfuhrmann can you export these for this? Or do you need me too?

**Comment by ekfuhrmann** [comment]
@jennabillingsley Learned a bit here. It seems that you are right that exporting back out of sketch is resulting in lower-quality images than we'd like. When taking the original assets, we're getting much higher quality images.

We should discuss this a bit further to make sure we have no issues with future case studies.
