### ISSUE TITLE
Rokt Case STudy: Spirit 12/4 divider 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#376]
<img width="549" alt="screen shot 2018-02-13 at 1 54 01 pm" src="https://user-images.githubusercontent.com/31738798/36167889-5fb21ec4-10c5-11e8-9417-609070bcc167.png">

the bottom edge has a border where it shouldn't

**Comment by jennabillingsley** [comment]
Fixed this in the new file
