### ISSUE TITLE
Rokt Case Study: Embarking On A Journey IMage

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#377]
![Screen Shot 2018-02-13 at 2.16.15 PM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/6bf4f32b-1cc2-4e24-8917-e9d57762176a)

Just an idea: would it be good to have a more complex animation, like in DesignLabs? (hope it doesn't make eric's job harder)

**Comment by jennabillingsley** [comment]
@theseangoodwin let's add this to our list.

**Comment by jennabillingsley** [comment]
Discussed this as a group... not going to animate this section given current time constraints.
