### ISSUE TITLE
Rokt Case Study: Hearing it here first 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#378]
![screen shot 2018-02-13 at 2 23 05 pm](https://user-images.githubusercontent.com/31738798/36169155-6da8029c-10c9-11e8-9bce-42981db3caf3.png)

I think that although it's representative of the Sydney trip, it's noticeably not a high enough quality image to include in the case study. 

Also, what is the purpose of having this section? I feel like we could maybe super briefly mention sydney/nyc somewhere in the challenge/solution area (ie something w/ this sentiment: After traveling to Sydney and NYC, we got to know Rokt customers better etc....). 

I see the relevancy of this section, but in the grand scheme of the case study, it comes across as random. Maybe it would help to relocate it to somewhere more relevant in the case study.

**Comment by jennabillingsley** [comment]
This is a difficult section to move now that the design is complete. Would change the headline to: **Grounded by research**

_This will hopefully help establish that everything above was grounded in the work we did prior._
