### ISSUE TITLE
Rokt Case Study: A roadmap to rock 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#379]
Is "A roadmap to rock" a common phrase? I'm not familiar with what it means. 
![screen shot 2018-02-13 at 2 29 17 pm](https://user-images.githubusercontent.com/31738798/36169460-4a7d9948-10ca-11e8-96c7-370515abd636.png)

The bottom edge dropshadow looks like it's too much because it looks like it's bleeding into the bottom part of the image itself.

**Comment by jennabillingsley** [comment]
@ekfuhrmann Fix this in the screenshot
