### ISSUE TITLE
Rokt case study: MOBILE Intro 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#382]
![Screen Shot 2018-02-13 at 4.42.12 PM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/ebffc8a6-a28f-4d0c-97de-d4376610b0e8)
galaxy chrome 

Are there supposed to be no KPIs?

**Comment by ekfuhrmann** [comment]
This is intentional.
