### ISSUE TITLE
Rokt case study: MOBILE disproportional images 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#384]
![Screen Shot 2018-02-13 at 4.51.03 PM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/27fb78a9-95e0-4caf-91ee-7c4146d904ef)
galaxy chome 

The divider looks very proportionally small 

Also, since this is mobile, how would we make that top image also look more proportional? I know we had touched on this in similar issues, so it's no big deal if this isn't possible. 

![screen shot 2018-02-13 at 4 58 03 pm](https://user-images.githubusercontent.com/31738798/36175966-252b8226-10df-11e8-9a84-b914eb217744.png)

**Comment by ekfuhrmann** [comment]
We don't have mobile layouts for our case studies, so most of the images scale proportionately.

Duplicate #350
