### ISSUE TITLE
Andpizza Case Study: Hero Intro missing on PC/Chrome

### ISSUE THREAD

**Issue by theastralj** [BraveUX/braveux#386]
![image](https://user-images.githubusercontent.com/1764989/36283057-32a3c0e2-1271-11e8-95ab-f67b7aee1c69.png)

**Comment by ekfuhrmann** [comment]
There were incorrectly two html files `andPizza.html` and `andpizza.html`. Only one of them had the updated JS, but it was not the one being given priority when loading the page. I've removed the errant `html` file and now it always calls the correct, updated page.
