### ISSUE TITLE
MHG Case Study: Borders 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#390]
Flow through a funnel 
![Screen Shot 2018-02-20 at 9.50.22 AM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/44fae13f-3e80-40ee-be5c-1819ed6ad7b4)

A true north for sales 
![Screen Shot 2018-02-20 at 9.50.08 AM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/f9e7a8da-9ce3-4b28-92ed-2b162c902fdd)

Thinking in green and blue
![Screen Shot 2018-02-20 at 9.51.05 AM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/8d85826b-76af-4b37-8927-a0927b51649b)

In the above images, there are border issues where under the browser header there is a white line on the edge (on my laptop but not on my desktop).

 In the last image, there is a white line on the bottom border of the overlaid browser (this is present in both desktop & laptop)

**Comment by ekfuhrmann** [comment]
Whoops, I only applied the fix for this on desktop displays. Added it to smaller sizes as well.
