### ISSUE TITLE
MHG Case Study: stock image page divider 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#391]
![Screen Shot 2018-02-20 at 9.59.03 AM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/1eac8a79-7aac-4f22-8afa-7b0d59cbe919)

Is there supposed to be copy on here? I'll be honest, it looks kinda awkwardly placed or that it shouldn't be missing copy, or maybe it should have a little less height?

**Comment by ekfuhrmann** [comment]
We use these types of breaks across all our case studies. I personally don't look at it like content is missing.

**Comment by theseangoodwin** [comment]
This divider no longer exists in the present case study.
