### ISSUE TITLE
MHG Case Study: Thinking in blue and green Animation 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#393]
![screen shot 2018-02-20 at 10 15 11 am](https://user-images.githubusercontent.com/31738798/36431951-f6d7eb60-1626-11e8-8259-7f007c865100.png)

![screen shot 2018-02-20 at 10 25 10 am](https://user-images.githubusercontent.com/31738798/36432516-5ea4b1dc-1628-11e8-9d37-6113c87eb971.png)

The animations didn't load until i was pretty far down the page (more so than when the other browser screens load)  - not sure if this is was coded similarly to the other browser animations, but i checked and it appeared to be slightly delayed

**Comment by ekfuhrmann** [comment]
This was a mistake. The bottom transition should've loaded sooner than it did. I've now fixed it.
