### ISSUE TITLE
MHG Case study: thinking in blue and green edges 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#397]
![Screen Shot 2018-02-20 at 10.25.55 AM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/2e2ed527-65fc-4949-b28d-752bb3236788)

upper right hand corner - wonky edge on the browser border. I acknowledge that these are two overlapped images, but not sure if this is purposeful

**Comment by ekfuhrmann** [comment]
The layering is intentional. Them not aligning correctly was not. I've actually resolved this issue with the frame fixes I pushed out for #390
