### ISSUE TITLE
Hurdlr Case Study: Intuitive Facts from front to back images 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#400]
![Screen Shot 2018-03-22 at 5.23.45 PM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/c7435454-f194-4c9d-92b1-c7d35ff8dea6)

Inconsistent corners. Some slightly rounded and some sharp.

**Comment by ekfuhrmann** [comment]
This was due to the images using the inappropriate `object-fit` property and then manually resizing the window.

Resizing the window should no longer cause any images to clip.
