### ISSUE TITLE
Hurdlr case study: mobile images top edges throughout 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#402]
Throughout, the mobile images top edges are sometimes a little to close to the border. ![Screen Shot 2018-03-22 at 5.28.10 PM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/3d3c1593-1105-4ce2-9692-c44c866e80a8)

**Comment by ekfuhrmann** [comment]
I gave a little bit of "bleed" space for the frames since as you scale it can sometimes flicker in the background as the scaling of the frame and img isn't always 1:1. That said, I've tightened up the bleed a bit so that the content fits better.
