### ISSUE TITLE
Hurdlr Case Study: "you just got paid" notification 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#403]
![Screen Shot 2018-03-22 at 5.55.34 PM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/acc907de-5102-4b2a-8c29-11d8198e6aa3)

- are we going to add that notification animation to the other two cards? 
- when the animation slightly bounces back up you can kinda see the mask on the top edge; the "3" also quivers.

**Comment by ekfuhrmann** [comment]
The notification icon is only intended to be on the first card. 

The clipping issue has been fixed, but the shake is actually a chrome render issue. I've tried to minimize the jitter as best as I could using `backface-visibility`, but beyond that there isn't too much more we can do that I know of.
