### ISSUE TITLE
Hurdlr Case Study: speed dial animation 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#404]
<img width="728" alt="screen shot 2018-03-22 at 5 53 23 pm" src="https://user-images.githubusercontent.com/31738798/37800900-d7a1056a-2dfa-11e8-8a7c-8bd567da293e.png">

Are we going to animate those numbers in slot machine fashion?

**Comment by ekfuhrmann** [comment]
No. It would be far too difficult to actually get the numbers to increase. Then too we'd need to figure out what we do if someone leaves this open for hours. Does it continually increase? It's such a minor element that I think we'd sooner want to just leave the numbers static but aligned evenly, than go about trying to think through how to animate and increase over time.
