### ISSUE TITLE
Hurdlr Case Study: leveraging a brand image edge 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#405]
![Screen Shot 2018-03-22 at 6.01.41 PM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/7634754d-433f-4911-b369-b7f8ad78ca8e)

Is there supposed to be that white edge there on the right hand border of the desktop screen?

**Comment by ekfuhrmann** [comment]
There is a minor border that gets pronounced due to the section bottom shadow, I'm fine with it.
