### ISSUE TITLE
Hurdlr Case Study: leveraging a brand bottom edge shadow 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#406]
![Screen Shot 2018-03-22 at 6.03.25 PM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/580d3679-308f-4f0c-bba5-fa73e261a678)

I haven't seen us use this pattern before. Not sure if this was purposeful or not.

**Comment by ekfuhrmann** [comment]
We use this pattern in a few different places such as [SMP](http://braveux.com/work/smp). Generally it uses a light shadow as opposed to a darker one like this.
