### ISSUE TITLE
Hurdlr Case STudy: page divider w/ icon animation

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#413]
![Screen Shot 2018-03-27 at 10.19.26 AM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/0991dfc3-7cce-4bd9-8b80-c60b0b5db9c5)

So for the most part everything animates correctly in this page divider. Except _sometimes_ the two icons to the right of the "plug" icon won't animate and just quickly appear like a flash.

**Comment by ekfuhrmann** [comment]
This seems to be an issue with the image asset not always loading by the time it animates in. Generally speaking, a user will not be loading the page from this point, so the animation should NOT flicker under normal user interaction.
