### ISSUE TITLE
Hurdlr Case Study: Intuitive Facts from Front to Back- Profit &Loss image 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#418]
![Screen Shot 2018-03-27 at 10.36.16 AM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/b0a3f017-e241-42fe-97c6-6797871c945d)

When at a smaller screen size (but still a plausible and normal screen size), the image cuts off.  Then as the screen size becomes smaller, more is cut off: 
![Screen Shot 2018-03-27 at 10.39.03 AM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/bd8cc204-3395-4bfa-9183-b0287902866b)

**Comment by ekfuhrmann** [comment]
Resolved in #400
