### ISSUE TITLE
Hurdlr Case Study MOBILE: Speed Dial Animation 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#421]
<img width="495" alt="screen shot 2018-03-27 at 10 56 38 am" src="https://user-images.githubusercontent.com/31738798/37975871-408401d4-31ae-11e8-9d05-02f82e079036.png">
iPhone 10; the animation doesn't work at all.

**Comment by ekfuhrmann** [comment]
Like #425, the pathing to these shadows and gradients needed to be absolute for Safari/iOS.
