### ISSUE TITLE
Hurdlr Case Study MOBILE: Typeface comparison alignment 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#423]
![Screen Shot 2018-03-27 at 1.58.18 PM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/180207f9-c040-4f65-b466-7ecf38bfcc51)
iPhone 10
I feel like there should be better left alignment w/ the typeface label/example and the caption/caption title.

**Comment by ekfuhrmann** [comment]
Agreed. This was due to the icons flex properties causing it to shrink. It has been fixed!
