### ISSUE TITLE
Hurdlr Case Study MOBILE: Testimonial 

### ISSUE THREAD

**Issue by gabrielataginya** [BraveUX/braveux#426]
![Screen Shot 2018-03-27 at 2.04.13 PM.png](https://images.zenhubusercontent.com/59e75702a468affe6df7237a/b88dcfaf-dd24-4381-9b61-c0e5495d1f02)

Should the short quote better left align with the long quote and should the short quote cover more lateral space to match how much space the long quote is allotted?

**Comment by ekfuhrmann** [comment]
They actually do align if you draw a line down from the short quotes Double Quote on the left.
